import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import { copy } from 'esbuild-plugin-copy'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    plugins: [
        copy({
            resolveFrom: 'cwd',
            assets: {
                from: ['./styles/*'],
                to: ['vault/.obsidian/plugins/generation/styles'],
            },
            watch: true,
        }),
        copy({
            resolveFrom: 'cwd',
            assets: {
                from: ['./manifest.json'],
                to: ['vault/.obsidian/plugins/generation/manifest.json'],
            },
            watch: true,
        }),
        copy({
            resolveFrom: 'cwd',
            assets: {
                from: ['./main.js'],
                to: ['vault/.obsidian/plugins/generation/main.js'],
            },
            watch: true,
        }),
    ],
})

if (prod) {
    await context.rebuild()
    process.exit(0)
} else {
    await context.watch()
}